### ISSUE TITLE
Initial 'help' command

### ISSUE THREAD

**Issue by CBPSC** [dnndev/Dnn.AdminExperience.Extensions#18]
On my very first install of Prompt I saw the line at the top " _Type 'help' to get a list of commands_".

I typed help and got an error
I typed 'help' and got an error 

(as seen in the attached image)

I was only able to see the help menu options when I typed "help" with double quotes. Suggestion is to list the word help with double quotes in the initial instructions.

I know this is rather small, but it did make me think about it a few times before I got it right :-) 

![image](https://cloud.githubusercontent.com/assets/4571863/22754078/5175d350-ee0c-11e6-800c-50834537894e.png)

**Comment by dnndev** [comment]
That is a bug. You should type help with no quotes.

**Comment by david-poindexter** [comment]
@CBPSC stated he typed help with no quotes.  
@dnndev I have not personally been able to replicate this behavior.  I have tried on 3 separate, clean installs (two in 9.0.1 and one in 9.0.0).

**Comment by CBPSC** [comment]
It works in the latest version of Prompt ;-)
