### ISSUE TITLE
Modules not deleting

### ISSUE THREAD

**Issue by CBPSC** [dnndev/Dnn.AdminExperience.Extensions#19]
I tested deleting pages and it worked, they show up in recycle bin.

I tested deleting a module and it is not working... as seen in attached screenshot

![image](https://cloud.githubusercontent.com/assets/4571863/22754521/d1860f0a-ee0d-11e6-9b43-b339b140d228.png)

**Comment by david-poindexter** [comment]
@CBPSC I was able to replicate this issue.  Prompt still shows the module in the list-modules commend immediately after running the delete-module command.  However, the module has in fact been PERMANENTLY deleted (not in Recycle Bin).  

@dnndev Not sure why Prompt still thinks the module exists.  My guess is the module wasn't "properly" deleted to start with.  I have not dug into the code, but you may want to make sure you are following "best practices" to delete the module.

**Comment by dnndev** [comment]
What happens if you `clear-cache` ?

**Comment by CBPSC** [comment]
after executing the clear-cache command it seemed to work. It did not continue to show the module as being present on the page.

**Comment by david-poindexter** [comment]
Clearing cache resolves the issue.  So perhaps you need to programmaticly clear cache for certain actions like this?

**Comment by dnndev** [comment]
Sorry for the delay... getting back to this.... There are two components of deleting a module (and a page). You `delete-module` and you then `purge-module`. Are you saying that after deletion and after purge the module still shows?

**Comment by david-poindexter** [comment]
@dnndev I will try that now.  I do not believe I was purging before.

**Comment by dnndev** [comment]
The reason I bring it up is because `delete` will put the page in the recycle bin (which you can see in the screen shot where it no longer has a page id associated with it [AddedToPages]). Purge is used to clear it from the Recycle Bin.

**Comment by david-poindexter** [comment]
@dnndev there is no purge-module command in the version I am running.  Is that new?
![screencapture_ 2017-02-15 11 58 am _967](https://cloud.githubusercontent.com/assets/4568451/22985352/26f5bcf2-f376-11e6-85c6-6f911bd8eb3b.png)

**Comment by CBPSC** [comment]
When I type delete-module 381 the module gets deleted, but yet does not show up in the Recycle Bin

**Comment by david-poindexter** [comment]
Something seems off here...the moduleid I deleted using module-delete was 353 by the way.

![screencapture_ 2017-02-15 12 06 pm _968](https://cloud.githubusercontent.com/assets/4568451/22985737/54ea9ae6-f377-11e6-8ce0-b0c91ae09d05.png)

**Comment by dnndev** [comment]
Module cache is now cleared when a module is permanently deleted via `delete-module`. This prevents the module from showing up when the `list-modules` command is executed.
