### ISSUE TITLE
Enhancement Request - Include options on new-page command

### ISSUE THREAD

**Issue by CBPSC** [dnndev/Dnn.AdminExperience.Extensions#20]
I created a page and after creating that page I saw it in the menu and wondered if there was a way I could create a page and tell it to not show up in the menu via the prompt. Once I thought about that I wondered if it would be possible to control the URL field as well. I'm not sure if this is possible, but just sharing. 

Wondering if a command such as:
*****   new-page About, About, /About, True 
would work where you are essentially entering
*****    new-page [Name],[Title],[URL/Path],[IncludeInMenu]

![image](https://cloud.githubusercontent.com/assets/4571863/22755043/86e0144e-ee0f-11e6-8d3e-56f6441fa561.png)

**Comment by dnndev** [comment]
type: help command-name to see the options.

**Comment by dnndev** [comment]
You can also type: help syntax   and: help learn for more info

**Comment by CBPSC** [comment]
This was included in most recent version. Closing this one. Nicely done sir!
