### ISSUE TITLE
Should "Home" have quotes in Get Page by name help docs? 

### ISSUE THREAD

**Issue by CBPSC** [dnndev/Dnn.AdminExperience.Extensions#32]
![quotes](https://cloud.githubusercontent.com/assets/4571863/22977080/4711f1a6-f35b-11e6-9b95-1034b6d81b57.png)

**Comment by dnndev** [comment]
This is an example of when quotes are required (spaces) and when they are not. One of the goals of Prompt is to reduce typing to a minimum. Optional quotes when possible is one way of achieving that.
