### ISSUE TITLE
Get-User Help Documentation Section Does Not Start off with an Options Table

### ISSUE THREAD

**Issue by CBPSC** [dnndev/Dnn.AdminExperience.Extensions#40]
Every command in the help documentation area that accepts parameters or "flags" starts off with a table that lists each parameter, then it describes them below. The Get-User help has the description, but does not have the table. 

Just a consistency in documentation issue.

**Comment by david-poindexter** [comment]
I'll be happy to take this one on, but may need some assistance with the exact desired Descriptions.

**Comment by CBPSC** [comment]
the command "List-Users" also lacks this "Options" table at the beginning

**Comment by david-poindexter** [comment]
@CBPSC I would recommend adding that as a separate issue.  Thanks!

**Comment by CBPSC** [comment]
On it..

**Comment by CBPSC** [comment]
Actually, I am incorrect here - the options table is there for the "list-users" command. I think there is another one somewhere that I was thinking about. I will try to track it down.
