### ISSUE TITLE
New-User Help Info Duplicated

### ISSUE THREAD

**Issue by CBPSC** [dnndev/Dnn.AdminExperience.Extensions#41]
![dup-new-user](https://cloud.githubusercontent.com/assets/4571863/22982174/57c7b4ac-f36c-11e6-8928-16762a17a796.png)

**Comment by dnndev** [comment]
I'm not sure what I'm seeing in the screen shot. It looks like you have executed the command `help new-user` twice.

**Comment by CBPSC** [comment]
Ah! I've been doing this for too long. My eyes are crossing up my brain. I will remove the duplicate issues I've filed. Sorry
