### ISSUE TITLE
Do String Fields Need Quotes in New-User Help Documentation?

### ISSUE THREAD

**Issue by CBPSC** [dnndev/Dnn.AdminExperience.Extensions#42]
![new-user-need-quotes](https://cloud.githubusercontent.com/assets/4571863/22982307/c91b940c-f36c-11e6-90b5-07f24a3bcf54.png)

**Comment by dnndev** [comment]
The rule for quotes in all commands is if there is a space or funky characters. Basically you can use --firstname Erik or --firstname "Erik"  but you have to use quotes for --firstname "Erik VB"
