### ISSUE TITLE
Visual separation between multiple help commands within same non-cleared window

### ISSUE THREAD

**Issue by david-poindexter** [dnndev/Dnn.AdminExperience.Extensions#53]
When a user runs multiple help commands without first performing a **cls** command, there is no clear separation between the previous help results.  I recommend a double HR separator or something like that to make it easier to distinguish between the multiple help sections.
 
![screencapture_ 2017-02-15 12 38 pm _969](https://cloud.githubusercontent.com/assets/4568451/22987119/bda42774-f37b-11e6-9f4b-a362bb04e5ce.png)

**Comment by dnndev** [comment]
Does the light blue bar with the command name not provide enough separation or am I missing your point?

**Comment by david-poindexter** [comment]
Sorry for the confusion.  I am just being a bit picky here.  :)  The command that was run (which is right above the light blue bar) becomes styled as normal text.  So it acts somewhat as a "visual connector" to the normal text right above it (which belongs to the previous help section).  I would recommend one of the following approaches:

- place a separator of sorts between the command and the previous help section (if applicable)
- style the command green (like it was when typed) and with the prompt '>'

I hope this helps.

**Comment by dnndev** [comment]
Changes like that will affect all displays, regardless of whether Help is being displayed. I like keeping the command green, but I'll have to see if it's possible given the way it's set up now. If not we may have to refactor the front-end somewhat

**Comment by david-poindexter** [comment]
Ah okay - I defer to your best judgement.  I believe making the old command styles green will help a lot visually.
