### ISSUE TITLE
Add `clear-log` command

### ISSUE THREAD

**Issue by david-poindexter** [dnndev/Dnn.AdminExperience.Extensions#62]
**Name:** `clear-log`
**Description:** This command will clear the EventLog.
**Options:** To be determined.

**Comment by dnndev** [comment]
For v.1 I don't think we need any options. The command should simple mimic the Clear Log button that SuperUser's have access to.

**Comment by david-poindexter** [comment]
Perfect, we have this working in dev and will submit a PR soon.
