### ISSUE TITLE
Shorten DateTime Displays

### ISSUE THREAD

**Issue by dnndev** [dnndev/Dnn.AdminExperience.Extensions#9]
Remove "T" and leave off fractional seconds.

**Comment by dnndev** [comment]
We should try and modify the display of times coming from DNN. Right now they are full dates/times, down to fractions of a second. I believe DNN includes the MomentJS library. If so, we can use that to format these on the client side -- or perhaps we should format them on the server since the server knows what is and is not a date.

**Comment by donker** [comment]
I think I've taken care of this.
